WebApplication5/ViewModels/RequestViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace WebApplication5.ViewModels
{
    public class RequestViewModel
    {
        public int Id { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        public string? FileName { get; set; }
        public string Status { get; set; }

        [ValidateNever]
        public IFormFile CV { get; set; }
        [ValidateNever]
        public bool IsApproved { get; set; }
    }
}

WebApplication5/Controllers/RequestController.cs
using AutoMapper;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using WebApplication5.Helper;
using WebApplication5.Interfaces;
using WebApplication5.Utility;
using WebApplication5.ViewModels;

namespace WebApplication5.Controllers
{
    public class RequestController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;
        private readonly IHostingEnvironment environment;
        public RequestController(IUnitOfWork unitOfWork, IMapper mapper, IHostingEnvironment environment)
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
            this.environment = environment;
        }
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Details(int? id)
        {
            if (id == null) return NotFound();
            var request = unitOfWork.RequestRepository.Get(id);
            if (request == null) return NotFound();

            var mapRequest = mapper.Map<Request, RequestViewModel>(request);
            return View(mapRequest);
        }
        public IActionResult Cancelled(RequestViewModel  requestVM)
        {

            var request = unitOfWork.RequestRepository.Get(requestVM.Id);
           
            request.Status = SD.RequestStatusDeleted;
            unitOfWork.RequestRepository.Update(request);
            TempData["success"] = "The appointment  has been cancelled";
            //SEND EMAIL
            return RedirectToAction("Index");
        }

        public IActionResult SendRequest()
        {
            return View();
        }
       [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SendRequest(RequestViewModel model)
        {
            if (model == null) return NotFound();
            if (ModelState.IsValid)
            {
                model.FileName = DocumentSettings.UploadFile(model.CV, "CVs");
                model.Status = SD.RequestStatusPending;
                var request = mapper.Map<RequestViewModel, Request>(model);
                unitOfWork.RequestRepository.Add(request);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        public IActionResult DownloadFile(string fileName)
        {
            //Build the File Path.
            string path = Path.Combine(this.environment.WebRootPath, "files/") + fileName;

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", fileName);
        }



        #region APIs 
        [HttpGet]
        public IActionResult GetAll()
        {
            var mapRequests = mapper.Map<IEnumerable<Request>, IEnumerable<RequestViewModel>>(unitOfWork.RequestRepository.GetAll());
            return Json(new { data = mapRequests });
        }
        #endregion
    }
}

WebApplication5/Views/Request/PartialViews/_CancelledRequestPartialView.cshtml
@model RequestViewModel
<div class="modal fade cancelled" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Cancelled Request</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <form asp-action="Cancelled" asp-controller="Request" class="appoinment-form">
                    <div class="mb-2">
                        <input asp-for="Id" hidden />
                        <p class="text-danger font-weight-bold">Are You Sure You Want To Cancelled this Request?!!</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-dark btn-round-full">Cancelled Request</button>
                        <button type="button" class="btn btn-secondary btn-round-full" onclick="OnCloseModalCancelled()">Close</button>

                    </div>
                </form>
            </div>

        </div>
    </div>
</div>